name: Documentation Request
description: Request new documentation or report outdated docs
title: "[DOCS] "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Need new documentation, or found something outdated? Let us know!

  - type: input
    id: email
    attributes:
      label: Hertie email
      description: Your @hertie-school.org or @students.hertie-school.org email
      placeholder: firstname.lastname@students.hertie-school.org
    validations:
      required: true

  - type: dropdown
    id: request_type
    attributes:
      label: Request type
      description: Are you requesting new docs or reporting an issue with existing docs?
      options:
        - New documentation
        - Outdated or incorrect documentation
    validations:
      required: true

  - type: textarea
    id: topic
    attributes:
      label: What documentation do you need or what is outdated?
      description: Describe the topic you need documented, or link to the outdated docs
      placeholder: |
        For new docs: How to set up a Python virtual environment on ds01...
        For outdated docs: The guide at docs/setup.md says to use Python 3.8 but we now use 3.11...
    validations:
      required: true

  - type: textarea
    id: searched
    attributes:
      label: What have you searched for?
      description: Where have you looked so far?
      placeholder: I searched the docs for... / I looked in the wiki for...
    validations:
      required: false

  - type: textarea
    id: usecase
    attributes:
      label: Your use case
      description: What are you trying to accomplish? This helps us write better docs.
      placeholder: I'm trying to... / I need this for my thesis work on...
    validations:
      required: false
